server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://100.127.112.49:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - target_label: 'server'
        replacement: 'oracle'
      - target_label: 'job'
        replacement: 'docker'

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          server: 'oracle'
          __path__: /var/log/syslog
